import coherent_states_squeezed_states_quantum_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace coherent_states_squeezed_states_quantum_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end coherent_states_squeezed_states_quantum_theorem_canonical_lane_mathlib
end HautevilleHouse
